### ISSUE TITLE
Add support to SF4

### ISSUE THREAD

**Issue by renatoaraujo** [contentful/ContentfulBundle#28]
Hello,

I am developing an application that should be integrated with Contentful and would like to know when Symfony 4 support will be available.
I'm seriously considering making a fork from this library but I have concerns about changing settings and so on.

Thanks

**Comment by dborsatto** [comment]
Hey @renatoaraujo,

I'm actively working on it, and hopefully I'll release something next week!

Davide

**Comment by renatoaraujo** [comment]
Thanks, looking forward to it :)

**Comment by Rabot18** [comment]
Hey @dborsatto !
I'm looking for it too, thx in advance ;)

**Comment by dborsatto** [comment]
Hey all,

I've just opened #29 , and tomorrow I will release version 3 of this bundle 🙂

**Comment by dborsatto** [comment]
Hello everyone,

I've just released an updated version of the bundle, which includes support to Symfony 4.
Because certain things are handled very differently in Symfony 4, the upgrade wasn't an easy process. For this reason I ask you to please test the bundle, and report issues should you find them. I'll soon try to get this bundle on the Symfony Flex registry, but in the meanwhile, feel free to reach out for any issue you might encounter!

Davide
